# 多平台配置示例
# 复制此文件为 platforms.yaml 并修改相应配置

platforms:
  # 智能记账服务（必需）
  accounting:
    enabled: true
    server_url: "http://localhost:3000"
    token: "your_accounting_token"
    account_book_id: "your_account_book_id"
  