# 多平台配置示例
# 复制此文件为 platforms.yaml 并修改相应配置

platforms:
  # 智能记账服务（必需）
  accounting:
    enabled: true
    server_url: "http://localhost:3000"
    token: "your_accounting_token"
    account_book_id: "your_account_book_id"
  
  # DIFY AI工作流平台
  dify:
    enabled: false  # 设置为 true 启用
    api_key: "your_dify_api_key"
    base_url: "https://api.dify.ai"
    workflow_id: "your_workflow_id"
    keywords: []  # 空数组表示处理所有消息，可设置关键词过滤
    # keywords: ["分析", "AI", "智能"]  # 只处理包含这些关键词的消息
  
  # COZE对话AI平台
  coze:
    enabled: false  # 设置为 true 启用
    api_token: "your_coze_api_token"
    bot_id: "your_coze_bot_id"
    base_url: "https://api.coze.com"
    # COZE会自动识别问句类型的消息
  
  # N8N自动化工作流平台
  n8n:
    enabled: false  # 设置为 true 启用
    webhook_url: "https://your-n8n-instance.com/webhook/your-webhook-id"
    api_key: "your_n8n_api_key"  # 可选，如果webhook需要认证
    triggers:  # 触发关键词
      - "自动化"
      - "workflow"
      - "执行"
      - "提醒"
      - "定时"

# 平台处理优先级
# 1. accounting - 智能记账（优先处理）
# 2. dify - AI工作流分析
# 3. coze - 对话AI回复
# 4. n8n - 自动化工作流

# 使用说明：
# 1. 每个平台可以独立启用/禁用
# 2. 消息会按优先级顺序处理
# 3. 只有相关的消息才会发送到对应平台
# 4. 平台可以并行处理同一条消息
# 5. 回复会根据平台设置决定是否发送到微信

# 平台相关性判断：
# - accounting: 处理所有消息
# - dify: 根据keywords配置或处理所有消息
# - coze: 自动识别问句类型（包含问号、疑问词等）
# - n8n: 根据triggers关键词匹配

# 回复策略：
# - 消息与记账无关：不回复微信
# - 记账成功/失败：回复详细信息
# - DIFY分析结果：根据工作流配置决定
# - COZE对话回复：通常都会回复
# - N8N工作流：根据工作流返回结果决定
